### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by continue98** [hiitiger/goverlay#28]
Hi.  I'm trying to use commands from the documentation to get an example, but on the command: ```npm run compile:electron``` getting errors:

```
> gelectron@1.0.0 compile:electron D:\dev\gelectron\client
> electron-rebuild -v 2.0.8

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn D:\dev\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\dev\\gelectron\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.8" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\dev\gelectron\electron-overlay
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 7

Error: gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn D:\dev\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\dev\\gelectron\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.8" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\dev\gelectron\electron-overlay
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 7
    at SafeSubscriber._error (D:\dev\gelectron\client\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (D:\dev\gelectron\client\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (D:\dev\gelectron\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:191:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! gelectron@1.0.0 compile:electron: `electron-rebuild -v 2.0.8`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the gelectron@1.0.0 compile:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\continue\AppData\Roaming\npm-cache\_logs\2019-10-29T14_56_31_034Z-debug.log
```

Debug log:

```
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v13.0.1
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [
6 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
6 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
6 verbose cli   'run',
6 verbose cli   'compile:electron'
6 verbose cli ]
7 info using npm@6.12.0
8 info using node@v13.0.1
9 verbose run-script [ 'precompile:electron', 'compile:electron', 'postcompile:electron' ]
10 info lifecycle gelectron@1.0.0~precompile:electron: gelectron@1.0.0
11 info lifecycle gelectron@1.0.0~compile:electron: gelectron@1.0.0
12 verbose lifecycle gelectron@1.0.0~compile:electron: unsafe-perm in lifecycle true
13 verbose lifecycle gelectron@1.0.0~compile:electron: PATH: C:\ProgramData\nvm\v13.0.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\dev\gelectron\client\node_modules\.bin;C:\Python27;c:\perl64\site\bin;c:\perl64\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\nvidia corporation\nvidia nvdlisr;c:\program files\dotnet\;c:\programdata\chocolatey\bin;c:\program files\openssh-win64;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\microsoft sql server\client sdk\odbc\170\tools\binn\;c:\program files\git\cmd;c:\program files\cmake\bin;c:\go\bin;c:\program files\llvm\bin;d:\dev\gnuwin32\bin;C:\Program Files\Microsoft Network Monitor 3\;D:\dev;C:\ProgramData\nvm;C:\Program Files\nodejs;C:\Python27;C:\Users\continue\AppData\Local\Microsoft\WindowsApps;C:\Users\continue\go\bin;C:\Users\continue\AppData\Local\Programs\Microsoft VS Code\bin;C:\TDM-GCC-64\bin;D:\dev;
14 verbose lifecycle gelectron@1.0.0~compile:electron: CWD: D:\dev\gelectron\client
15 silly lifecycle gelectron@1.0.0~compile:electron: Args: [ '/d /s /c', 'electron-rebuild -v 2.0.8' ]
16 silly lifecycle gelectron@1.0.0~compile:electron: Returned: code: 4294967295  signal: null
17 info lifecycle gelectron@1.0.0~compile:electron: Failed to exec compile:electron script
18 verbose stack Error: gelectron@1.0.0 compile:electron: `electron-rebuild -v 2.0.8`
18 verbose stack Exit status 4294967295
18 verbose stack     at EventEmitter.<anonymous> (C:\ProgramData\nvm\v13.0.1\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:210:5)
18 verbose stack     at ChildProcess.<anonymous> (C:\ProgramData\nvm\v13.0.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:210:5)
18 verbose stack     at maybeClose (internal/child_process.js:1028:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
19 verbose pkgid gelectron@1.0.0
20 verbose cwd D:\dev\gelectron\client
21 verbose Windows_NT 10.0.17763
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile:electron"
23 verbose node v13.0.1
24 verbose npm  v6.12.0
25 error code ELIFECYCLE
26 error errno 4294967295
27 error gelectron@1.0.0 compile:electron: `electron-rebuild -v 2.0.8`
27 error Exit status 4294967295
28 error Failed at the gelectron@1.0.0 compile:electron script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 4294967295, true ]
```

I am use: 
```
node --version
v13.0.1
```
```
python --version
Python 2.7.13
```
```
node-gyp --version
v6.0.0
```

```
Visual Studio 2019 / Windows 10
```

**Comment by daMichl** [comment]
found a workaround:
https://github.com/nodejs/node-gyp/issues/1747#issuecomment-491692750
